version: "3"

services:
  spending_app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./spending_app:/spending_app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"