# Generated by Django 3.2.7 on 2021-09-12 13:21

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='image',
            field=models.ImageField(null=True, upload_to=api.models.transaction_image_file_path),
        ),
    ]
